name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Podman
        uses: redhat-actions/podman-login@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          podman build -t haircut:postgres .

      - name: Test the application
        run: |
          echo "remove test, do it if you want"
          # podman run --rm haircut:postgres /haircut-app --version

      - name: Push to Docker Hub
        run: |
          podman tag haircut:postgres docker.io/${{ secrets.DOCKER_USERNAME }}/haircut:postgres
          podman push docker.io/${{ secrets.DOCKER_USERNAME }}/haircut:postgres

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      # PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      TAILSCALE_SERVER_IP: 100.72.100.119 # Ganti dengan IP Tailscale server Anda
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 100.72.100.119
          username: server-1
          password: ninja
          port: 22
          script: |
            echo "Deploying script to remote server..."
            # Pull the latest image
            podman pull docker.io/balinux/haircut:postgres

            # jalankan tahap ini untuk pertama kali deploy container
            # atau jika tidak menggunakan systemd

            # # Stop the currently running container (if any)
            #
            # podman stop haircut-postgres-ga || true
            # podman rm haircut-postgres-ga || true
            #
            # # Run the new container
            # podman run -d --name haircut-postgres-ga -p 8886:8888 docker.io/balinux/haircut:postgres

            # cukup jalankan ini jika mengguakan podman di systemd
            systemctl --user restart container-haircut-postgres-ga.service
