name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Podman
        uses: redhat-actions/podman-login@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build the Docker image
      #   run: |
      #     podman build -t haircut:postgres .
      #
      # - name: Test the application
      #   run: |
      #     echo "remove test, do it if you want"
      #     # podman run --rm haircut:postgres /haircut-app --version
      #
      # - name: Push to Docker Hub
      #   run: |
      #     podman tag haircut:postgres docker.io/${{ secrets.DOCKER_USERNAME }}/haircut:postgres
      #     podman push docker.io/${{ secrets.DOCKER_USERNAME }}/haircut:postgres

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy to server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Deploying to server..."
          echo "$PWD"
          # mkdir -p ~/.ssh
          # echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          # chmod 600 ~/.ssh/id_rsa
          # ssh-keyscan -H myserver.com >> ~/.ssh/known_hosts
          # ssh -i ~/.ssh/id_rsa user@myserver.com 'bash -s' < deploy_script.sh
